export type SeedDifficulty = "EASY" | "MEDIUM" | "HARD" | "CHALLENGE";
export type SeedCategory =
  | "ARITHMETIC"
  | "ALGEBRA"
  | "GEOMETRY"
  | "FRACTIONS"
  | "NUMBER_THEORY"
  | "WORD_PROBLEMS"
  | "LOGIC"
  | "PROBABILITY"
  | "TRIGONOMETRY"
  | "CALCULUS"
  | "STATISTICS";
export type SeedAgeGroup =
  | "AGE_8_10"
  | "AGE_10_12"
  | "AGE_12_14"
  | "AGE_14_16"
  | "AGE_16_18";

export interface SeedQuestion {
  titleEn: string;
  titleZh: string;
  contentEn: string;
  contentZh: string;
  difficulty: SeedDifficulty;
  category: SeedCategory;
  ageGroup: SeedAgeGroup;
  answer: string;
  answerExplainEn?: string;
  answerExplainZh?: string;
  hints: Array<{ en: string; zh: string }>;
  animationConfig: Record<string, unknown>;
  funFactEn?: string;
  funFactZh?: string;
  isPublished: boolean;
  sortOrder: number;
  tags?: string[];
}

interface Blueprint {
  titleEn: string;
  titleZh: string;
  contentEn: string;
  contentZh: string;
  difficulty: SeedDifficulty;
  category: SeedCategory;
  ageGroup: SeedAgeGroup;
  answer: string;
  answerExplainEn: string;
  answerExplainZh: string;
  funFactEn?: string;
  funFactZh?: string;
  animationConfig?: Record<string, unknown>;
  standards?: string[];
}

const DEFAULT_HINTS = [
  {
    en: "Break the problem into smaller steps.",
    zh: "把问题拆成更小的步骤。",
  },
  {
    en: "Check whether your final answer is reasonable.",
    zh: "检查你的最终答案是否合理。",
  },
];

const BLUEPRINTS: Blueprint[] = [
  // Elementary (US Grades 3-5)
  {
    titleEn: "Place Value Patrol",
    titleZh: "数位巡逻队",
    contentEn: "Write 4 thousands, 7 hundreds, 2 tens, and 5 ones as a number.",
    contentZh: "把4个千、7个百、2个十和5个一写成数字。",
    difficulty: "EASY",
    category: "ARITHMETIC",
    ageGroup: "AGE_8_10",
    answer: "4725",
    answerExplainEn: "4000 + 700 + 20 + 5 = 4725.",
    answerExplainZh: "4000 + 700 + 20 + 5 = 4725。",
    animationConfig: { type: "number_combine", numbers: [4000, 700, 20, 5], operation: "add" },
  },
  {
    titleEn: "Round to Hundreds",
    titleZh: "四舍五入到百位",
    contentEn: "Round 3,648 to the nearest hundred.",
    contentZh: "把3,648四舍五入到最近的百位。",
    difficulty: "EASY",
    category: "ARITHMETIC",
    ageGroup: "AGE_8_10",
    answer: "3600",
    answerExplainEn: "The tens digit is 4, so round down to 3,600.",
    answerExplainZh: "十位是4，所以向下取整到3,600。",
    animationConfig: { type: "number_journey", range: [3500, 3700], highlights: [3600, 3648] },
  },
  {
    titleEn: "Multiply in Parts",
    titleZh: "分配律乘法",
    contentEn: "Compute 23 × 6.",
    contentZh: "计算23 × 6。",
    difficulty: "EASY",
    category: "ARITHMETIC",
    ageGroup: "AGE_8_10",
    answer: "138",
    answerExplainEn: "(20 × 6) + (3 × 6) = 120 + 18 = 138.",
    answerExplainZh: "(20 × 6) + (3 × 6) = 120 + 18 = 138。",
    animationConfig: { type: "number_combine", numbers: [120, 18], operation: "add" },
  },
  {
    titleEn: "Long Division Check",
    titleZh: "长除法检查",
    contentEn: "What is 168 ÷ 8?",
    contentZh: "168 ÷ 8 等于多少？",
    difficulty: "EASY",
    category: "ARITHMETIC",
    ageGroup: "AGE_10_12",
    answer: "21",
    answerExplainEn: "8 goes into 16 two times and into 8 one time, so 21.",
    answerExplainZh: "8进16有2次，进8有1次，所以是21。",
    animationConfig: { type: "number_journey", range: [0, 25], highlights: [21] },
  },
  {
    titleEn: "Equivalent Fraction Match",
    titleZh: "等值分数配对",
    contentEn: "Fill in: 3/4 = ?/20",
    contentZh: "填空：3/4 = ?/20",
    difficulty: "EASY",
    category: "FRACTIONS",
    ageGroup: "AGE_10_12",
    answer: "15",
    answerExplainEn: "Multiply numerator and denominator by 5. 3 × 5 = 15.",
    answerExplainZh: "分子分母同时乘5。3 × 5 = 15。",
    animationConfig: { type: "pizza_slice", totalSlices: 20, eatenSlices: 5 },
  },
  {
    titleEn: "Decimal to Fraction",
    titleZh: "小数化分数",
    contentEn: "Write 0.25 as a fraction in simplest form.",
    contentZh: "把0.25写成最简分数。",
    difficulty: "MEDIUM",
    category: "FRACTIONS",
    ageGroup: "AGE_10_12",
    answer: "1/4",
    answerExplainEn: "0.25 = 25/100 = 1/4.",
    answerExplainZh: "0.25 = 25/100 = 1/4。",
    animationConfig: { type: "pizza_slice", totalSlices: 4, eatenSlices: 3 },
  },
  {
    titleEn: "Area of Rectangle",
    titleZh: "长方形面积",
    contentEn: "A rectangle is 9 cm by 4 cm. What is its area?",
    contentZh: "一个长方形长9厘米、宽4厘米。面积是多少？",
    difficulty: "EASY",
    category: "GEOMETRY",
    ageGroup: "AGE_8_10",
    answer: "36",
    answerExplainEn: "Area = length × width = 9 × 4 = 36.",
    answerExplainZh: "面积 = 长 × 宽 = 9 × 4 = 36。",
    animationConfig: { type: "number_combine", numbers: [9, 4], operation: "multiply" },
  },
  {
    titleEn: "Perimeter Path",
    titleZh: "周长路线",
    contentEn: "A rectangle has length 12 and width 5. Find the perimeter.",
    contentZh: "长方形长12、宽5。求周长。",
    difficulty: "EASY",
    category: "GEOMETRY",
    ageGroup: "AGE_8_10",
    answer: "34",
    answerExplainEn: "Perimeter = 2 × (12 + 5) = 34.",
    answerExplainZh: "周长 = 2 × (12 + 5) = 34。",
    animationConfig: { type: "number_combine", numbers: [12, 5, 12, 5], operation: "add" },
  },
  {
    titleEn: "Volume of a Box",
    titleZh: "长方体体积",
    contentEn: "A box has dimensions 5, 3, and 2. What is the volume?",
    contentZh: "一个长方体的长宽高是5、3、2。体积是多少？",
    difficulty: "MEDIUM",
    category: "GEOMETRY",
    ageGroup: "AGE_10_12",
    answer: "30",
    answerExplainEn: "Volume = 5 × 3 × 2 = 30 cubic units.",
    answerExplainZh: "体积 = 5 × 3 × 2 = 30立方单位。",
    animationConfig: { type: "number_combine", numbers: [5, 3, 2], operation: "multiply" },
  },
  {
    titleEn: "Line Plot Read",
    titleZh: "线形图读数",
    contentEn: "Data: 2, 4, 4, 5, 5, 5, 7. What is the median?",
    contentZh: "数据：2, 4, 4, 5, 5, 5, 7。中位数是多少？",
    difficulty: "MEDIUM",
    category: "STATISTICS",
    ageGroup: "AGE_10_12",
    answer: "5",
    answerExplainEn: "There are 7 numbers, so the 4th value is the median: 5.",
    answerExplainZh: "一共7个数，所以第4个数是中位数：5。",
    animationConfig: { type: "number_journey", range: [1, 8], highlights: [2, 4, 5, 7] },
  },

  // Middle School (US Grades 6-8)
  {
    titleEn: "Ratio Builder",
    titleZh: "比率构建",
    contentEn: "If the ratio of red to blue marbles is 3:5 and there are 15 blue marbles, how many red marbles are there?",
    contentZh: "红球和蓝球的比是3:5。如果蓝球有15个，红球有多少个？",
    difficulty: "MEDIUM",
    category: "WORD_PROBLEMS",
    ageGroup: "AGE_12_14",
    answer: "9",
    answerExplainEn: "Scale factor is 3 (because 5 → 15). So red is 3 × 3 = 9.",
    answerExplainZh: "倍数是3（因为5变15）。所以红球是3 × 3 = 9。",
    animationConfig: { type: "candy_jar", red: 9, blue: 15, green: 0 },
  },
  {
    titleEn: "Unit Rate Sprint",
    titleZh: "单位率冲刺",
    contentEn: "A car goes 180 miles in 3 hours. What is the unit rate in miles per hour?",
    contentZh: "一辆车3小时行驶180英里。单位速度（英里/小时）是多少？",
    difficulty: "MEDIUM",
    category: "WORD_PROBLEMS",
    ageGroup: "AGE_12_14",
    answer: "60",
    answerExplainEn: "Unit rate is 180 ÷ 3 = 60 miles per hour.",
    answerExplainZh: "单位率是180 ÷ 3 = 60英里/小时。",
    animationConfig: { type: "number_journey", range: [0, 80], highlights: [60] },
  },
  {
    titleEn: "Percent Discount",
    titleZh: "折扣百分比",
    contentEn: "A $80 jacket is on sale for 25% off. What is the sale price?",
    contentZh: "一件80美元的夹克打75折（减25%）。现价是多少？",
    difficulty: "MEDIUM",
    category: "WORD_PROBLEMS",
    ageGroup: "AGE_12_14",
    answer: "60",
    answerExplainEn: "25% of 80 is 20, so 80 - 20 = 60.",
    answerExplainZh: "80的25%是20，所以80 - 20 = 60。",
    animationConfig: { type: "number_combine", numbers: [80, -20], operation: "add" },
  },
  {
    titleEn: "Integer Elevator",
    titleZh: "整数电梯",
    contentEn: "Start at -4 and move up 11 floors. What floor are you on now?",
    contentZh: "从-4层出发，上升11层。你现在在几层？",
    difficulty: "EASY",
    category: "NUMBER_THEORY",
    ageGroup: "AGE_12_14",
    answer: "7",
    answerExplainEn: "-4 + 11 = 7.",
    answerExplainZh: "-4 + 11 = 7。",
    animationConfig: { type: "number_journey", range: [-10, 12], highlights: [-4, 7] },
  },
  {
    titleEn: "Solve One-Step Equation",
    titleZh: "一元一步方程",
    contentEn: "Solve: x + 9 = 27",
    contentZh: "解方程：x + 9 = 27",
    difficulty: "EASY",
    category: "ALGEBRA",
    ageGroup: "AGE_12_14",
    answer: "18",
    answerExplainEn: "Subtract 9 from both sides: x = 18.",
    answerExplainZh: "两边都减9：x = 18。",
    animationConfig: { type: "balance_scale", leftSide: { expression: "x + 9" }, rightSide: { value: 27 } },
  },
  {
    titleEn: "Solve Two-Step Equation",
    titleZh: "一元两步方程",
    contentEn: "Solve: 3x - 5 = 19",
    contentZh: "解方程：3x - 5 = 19",
    difficulty: "MEDIUM",
    category: "ALGEBRA",
    ageGroup: "AGE_12_14",
    answer: "8",
    answerExplainEn: "Add 5: 3x = 24. Divide by 3: x = 8.",
    answerExplainZh: "先加5：3x = 24。再除以3：x = 8。",
    animationConfig: { type: "balance_scale", leftSide: { expression: "3x - 5" }, rightSide: { value: 19 } },
  },
  {
    titleEn: "Proportional Table",
    titleZh: "正比例表",
    contentEn: "If y is proportional to x and y = 18 when x = 6, what is y when x = 10?",
    contentZh: "如果y与x成正比，且x=6时y=18，那么x=10时y是多少？",
    difficulty: "MEDIUM",
    category: "ALGEBRA",
    ageGroup: "AGE_12_14",
    answer: "30",
    answerExplainEn: "Unit rate is 18/6 = 3, so y = 3 × 10 = 30.",
    answerExplainZh: "单位比是18/6=3，所以y=3×10=30。",
    animationConfig: { type: "number_combine", numbers: [3, 10], operation: "multiply" },
  },
  {
    titleEn: "Angles on a Line",
    titleZh: "同一直线角",
    contentEn: "Two adjacent angles on a straight line are (x + 20)° and (2x - 10)°. Find x.",
    contentZh: "同一直线上的两个邻角分别是(x + 20)°和(2x - 10)°。求x。",
    difficulty: "HARD",
    category: "GEOMETRY",
    ageGroup: "AGE_14_16",
    answer: "56.6667",
    answerExplainEn: "They sum to 180: x+20+2x-10=180 => 3x+10=180 => x=170/3≈56.6667.",
    answerExplainZh: "邻角和为180：x+20+2x-10=180 => 3x+10=180 => x=170/3≈56.6667。",
    animationConfig: { type: "triangle_angles", angles: [120, 60, 0] },
  },
  {
    titleEn: "Probability Spinner",
    titleZh: "转盘概率",
    contentEn: "A spinner has 8 equal sections, and 3 are blue. What is P(blue)?",
    contentZh: "一个转盘有8个等分区域，其中3个是蓝色。求P(蓝色)。",
    difficulty: "EASY",
    category: "PROBABILITY",
    ageGroup: "AGE_12_14",
    answer: "3/8",
    answerExplainEn: "Probability is favorable over total: 3/8.",
    answerExplainZh: "概率=有利结果/总结果=3/8。",
    animationConfig: { type: "candy_jar", blue: 3, red: 5, green: 0 },
  },
  {
    titleEn: "Mean Absolute Deviation",
    titleZh: "平均绝对离差",
    contentEn: "Data set: 4, 6, 8. What is the mean absolute deviation (MAD)?",
    contentZh: "数据集：4, 6, 8。平均绝对离差（MAD）是多少？",
    difficulty: "MEDIUM",
    category: "STATISTICS",
    ageGroup: "AGE_14_16",
    answer: "1.3333",
    answerExplainEn: "Mean is 6. Distances are 2,0,2. MAD=(2+0+2)/3=4/3≈1.3333.",
    answerExplainZh: "平均数是6，离差为2、0、2。MAD=(2+0+2)/3=4/3≈1.3333。",
    animationConfig: { type: "number_journey", range: [0, 10], highlights: [4, 6, 8] },
  },

  // High School (US Grades 9-12)
  {
    titleEn: "Slope from Two Points",
    titleZh: "两点求斜率",
    contentEn: "Find the slope through points (2, 5) and (6, 13).",
    contentZh: "求经过点(2,5)和(6,13)的直线斜率。",
    difficulty: "MEDIUM",
    category: "ALGEBRA",
    ageGroup: "AGE_14_16",
    answer: "2",
    answerExplainEn: "m = (13 - 5) / (6 - 2) = 8/4 = 2.",
    answerExplainZh: "m = (13 - 5) / (6 - 2) = 8/4 = 2。",
    animationConfig: { type: "number_journey", range: [0, 14], highlights: [2, 5, 6, 13] },
  },
  {
    titleEn: "Linear Function Value",
    titleZh: "线性函数代值",
    contentEn: "For f(x) = 3x - 7, find f(9).",
    contentZh: "已知f(x)=3x-7，求f(9)。",
    difficulty: "MEDIUM",
    category: "ALGEBRA",
    ageGroup: "AGE_14_16",
    answer: "20",
    answerExplainEn: "f(9)=3×9-7=27-7=20.",
    answerExplainZh: "f(9)=3×9-7=27-7=20。",
    animationConfig: { type: "number_combine", numbers: [27, -7], operation: "add" },
  },
  {
    titleEn: "System by Elimination",
    titleZh: "消元解方程组",
    contentEn: "Solve the system: x + y = 11 and x - y = 3. Find x.",
    contentZh: "解方程组：x+y=11，x-y=3。求x。",
    difficulty: "MEDIUM",
    category: "ALGEBRA",
    ageGroup: "AGE_14_16",
    answer: "7",
    answerExplainEn: "Add equations: 2x=14, so x=7.",
    answerExplainZh: "两式相加得2x=14，所以x=7。",
    animationConfig: { type: "balance_scale", leftSide: { expression: "x+y" }, rightSide: { value: 11 } },
  },
  {
    titleEn: "Quadratic Roots",
    titleZh: "二次方程根",
    contentEn: "Solve: x^2 - 9 = 0. Give the positive root.",
    contentZh: "解方程x^2-9=0。写出正根。",
    difficulty: "MEDIUM",
    category: "ALGEBRA",
    ageGroup: "AGE_14_16",
    answer: "3",
    answerExplainEn: "x^2=9 so x=±3; positive root is 3.",
    answerExplainZh: "x^2=9，所以x=±3；正根是3。",
    animationConfig: { type: "number_journey", range: [-5, 5], highlights: [-3, 3] },
  },
  {
    titleEn: "Vertex of Parabola",
    titleZh: "抛物线顶点",
    contentEn: "For y = (x - 4)^2 + 1, what is the x-coordinate of the vertex?",
    contentZh: "对于y=(x-4)^2+1，顶点的x坐标是多少？",
    difficulty: "MEDIUM",
    category: "ALGEBRA",
    ageGroup: "AGE_14_16",
    answer: "4",
    answerExplainEn: "Vertex form y=(x-h)^2+k has x-coordinate h=4.",
    answerExplainZh: "顶点式y=(x-h)^2+k的x坐标为h=4。",
    animationConfig: { type: "number_journey", range: [0, 8], highlights: [4] },
  },
  {
    titleEn: "Exponent Rule",
    titleZh: "指数法则",
    contentEn: "Simplify 2^3 × 2^4.",
    contentZh: "化简2^3 × 2^4。",
    difficulty: "EASY",
    category: "ALGEBRA",
    ageGroup: "AGE_14_16",
    answer: "128",
    answerExplainEn: "Same base: add exponents. 2^(3+4)=2^7=128.",
    answerExplainZh: "同底数相乘指数相加：2^(3+4)=2^7=128。",
    animationConfig: { type: "number_combine", numbers: [2, 2, 2, 2, 2, 2, 2], operation: "multiply" },
  },
  {
    titleEn: "Right Triangle Ratio",
    titleZh: "直角三角比",
    contentEn: "In a right triangle, opposite side is 3 and hypotenuse is 5. What is sin(theta)?",
    contentZh: "直角三角形中，对边是3，斜边是5。sin(theta)是多少？",
    difficulty: "MEDIUM",
    category: "TRIGONOMETRY",
    ageGroup: "AGE_14_16",
    answer: "3/5",
    answerExplainEn: "sin(theta)=opposite/hypotenuse=3/5.",
    answerExplainZh: "sin(theta)=对边/斜边=3/5。",
    animationConfig: { type: "triangle_angles", angles: [37, 53, 90] },
  },
  {
    titleEn: "Tangent Special Angle",
    titleZh: "特殊角正切",
    contentEn: "What is tan(45°)?",
    contentZh: "tan(45°)等于多少？",
    difficulty: "EASY",
    category: "TRIGONOMETRY",
    ageGroup: "AGE_14_16",
    answer: "1",
    answerExplainEn: "In a 45-45-90 triangle, opposite equals adjacent, so tan=1.",
    answerExplainZh: "45-45-90三角形中对边等于邻边，所以tan=1。",
    animationConfig: { type: "triangle_angles", angles: [45, 45, 90] },
  },
  {
    titleEn: "Unit Circle Cosine",
    titleZh: "单位圆余弦",
    contentEn: "What is cos(60°)?",
    contentZh: "cos(60°)是多少？",
    difficulty: "MEDIUM",
    category: "TRIGONOMETRY",
    ageGroup: "AGE_14_16",
    answer: "1/2",
    answerExplainEn: "From the unit circle special angles, cos(60°)=1/2.",
    answerExplainZh: "根据单位圆特殊角，cos(60°)=1/2。",
    animationConfig: { type: "number_journey", range: [0, 1], highlights: [0.5] },
  },
  {
    titleEn: "Derivative Power Rule",
    titleZh: "导数幂函数法则",
    contentEn: "Find d/dx of x^4.",
    contentZh: "求x^4的导数d/dx。",
    difficulty: "HARD",
    category: "CALCULUS",
    ageGroup: "AGE_16_18",
    answer: "4x^3",
    answerExplainEn: "Power rule: d/dx x^n = n x^(n-1).",
    answerExplainZh: "幂函数求导法则：d/dx x^n = n x^(n-1)。",
    animationConfig: { type: "number_journey", range: [1, 5], highlights: [4, 3] },
  },
  {
    titleEn: "Derivative of Linear",
    titleZh: "一次函数导数",
    contentEn: "Find d/dx of (7x - 2).",
    contentZh: "求(7x - 2)的导数。",
    difficulty: "MEDIUM",
    category: "CALCULUS",
    ageGroup: "AGE_16_18",
    answer: "7",
    answerExplainEn: "Derivative of ax+b is a, so derivative is 7.",
    answerExplainZh: "ax+b的导数是a，所以结果是7。",
    animationConfig: { type: "number_journey", range: [0, 10], highlights: [7] },
  },
  {
    titleEn: "Integral Basic",
    titleZh: "基础积分",
    contentEn: "Compute ∫ 2x dx.",
    contentZh: "计算∫ 2x dx。",
    difficulty: "HARD",
    category: "CALCULUS",
    ageGroup: "AGE_16_18",
    answer: "x^2 + C",
    answerExplainEn: "Antiderivative of 2x is x^2, plus constant C.",
    answerExplainZh: "2x的原函数是x^2，再加常数C。",
    animationConfig: { type: "number_combine", numbers: [2, 1], operation: "add" },
  },
  {
    titleEn: "Mean from Table",
    titleZh: "表格求平均",
    contentEn: "Scores are 70, 80, 90, 100. What is the mean?",
    contentZh: "成绩为70、80、90、100。平均数是多少？",
    difficulty: "EASY",
    category: "STATISTICS",
    ageGroup: "AGE_14_16",
    answer: "85",
    answerExplainEn: "(70+80+90+100)/4 = 340/4 = 85.",
    answerExplainZh: "(70+80+90+100)/4 = 340/4 = 85。",
    animationConfig: { type: "number_combine", numbers: [70, 80, 90, 100], operation: "add" },
  },
  {
    titleEn: "Standard Deviation Intuition",
    titleZh: "标准差直觉",
    contentEn: "Which data set has larger spread: A={5,5,5,5} or B={2,5,8,11}? Answer A or B.",
    contentZh: "哪组数据离散程度更大：A={5,5,5,5} 还是 B={2,5,8,11}？回答A或B。",
    difficulty: "MEDIUM",
    category: "STATISTICS",
    ageGroup: "AGE_16_18",
    answer: "B",
    answerExplainEn: "Set B varies much more around its center than A.",
    answerExplainZh: "B组围绕中心的波动更大。",
    animationConfig: { type: "number_journey", range: [0, 12], highlights: [2, 5, 8, 11] },
  },
  {
    titleEn: "Independent Events",
    titleZh: "独立事件",
    contentEn: "Flip a fair coin twice. What is the probability of getting two heads?",
    contentZh: "抛一枚公平硬币两次。两次都正面的概率是多少？",
    difficulty: "MEDIUM",
    category: "PROBABILITY",
    ageGroup: "AGE_14_16",
    answer: "1/4",
    answerExplainEn: "P(HH)=1/2 × 1/2 = 1/4.",
    answerExplainZh: "P(HH)=1/2 × 1/2 = 1/4。",
    animationConfig: { type: "candy_jar", red: 1, blue: 3, green: 0 },
  },
  {
    titleEn: "Binomial Coefficient",
    titleZh: "二项式系数",
    contentEn: "How many ways can you choose 2 students from 5?",
    contentZh: "从5名学生中选2名，有多少种选法？",
    difficulty: "HARD",
    category: "STATISTICS",
    ageGroup: "AGE_16_18",
    answer: "10",
    answerExplainEn: "Use combinations: C(5,2)=5×4/(2×1)=10.",
    answerExplainZh: "用组合数：C(5,2)=5×4/(2×1)=10。",
    animationConfig: { type: "number_combine", numbers: [5, 4], operation: "multiply" },
  },
  {
    titleEn: "Exponential Growth",
    titleZh: "指数增长",
    contentEn: "A bacteria count doubles every hour. Starting from 6, how many after 4 hours?",
    contentZh: "细菌数量每小时翻倍。起始为6，4小时后有多少？",
    difficulty: "MEDIUM",
    category: "ALGEBRA",
    ageGroup: "AGE_14_16",
    answer: "96",
    answerExplainEn: "6 × 2^4 = 6 × 16 = 96.",
    answerExplainZh: "6 × 2^4 = 6 × 16 = 96。",
    animationConfig: { type: "number_journey", range: [0, 100], highlights: [6, 12, 24, 48, 96] },
  },
  {
    titleEn: "Logarithm Basics",
    titleZh: "对数基础",
    contentEn: "Solve: log10(1000) = ?",
    contentZh: "求：log10(1000) = ?",
    difficulty: "HARD",
    category: "ALGEBRA",
    ageGroup: "AGE_16_18",
    answer: "3",
    answerExplainEn: "10^3 = 1000, so log10(1000)=3.",
    answerExplainZh: "因为10^3=1000，所以log10(1000)=3。",
    animationConfig: { type: "number_journey", range: [0, 5], highlights: [3] },
    standards: ["CCSS-HSF-LE-A1", "CCSS-HSF-LE-A2"],
  },
];

const HIGH_SCHOOL_EXTENSIONS: Blueprint[] = [
  {
    titleEn: "Function Notation",
    titleZh: "函数符号",
    contentEn: "If g(x) = 2x + 1, what is g(7)?",
    contentZh: "若g(x)=2x+1，求g(7)。",
    difficulty: "EASY",
    category: "ALGEBRA",
    ageGroup: "AGE_14_16",
    answer: "15",
    answerExplainEn: "g(7)=2*7+1=15.",
    answerExplainZh: "g(7)=2*7+1=15。",
    animationConfig: { type: "number_combine", numbers: [14, 1], operation: "add" },
    standards: ["CCSS-HSF-IF-A2"],
  },
  {
    titleEn: "Arithmetic Sequence",
    titleZh: "等差数列",
    contentEn: "Sequence: 5, 9, 13, ... What is the 6th term?",
    contentZh: "数列5, 9, 13, ... 第6项是多少？",
    difficulty: "MEDIUM",
    category: "ALGEBRA",
    ageGroup: "AGE_14_16",
    answer: "25",
    answerExplainEn: "Common difference is 4. a6 = 5 + 5*4 = 25.",
    answerExplainZh: "公差是4。a6 = 5 + 5*4 = 25。",
    standards: ["CCSS-HSF-BF-A2"],
  },
  {
    titleEn: "Geometric Sequence",
    titleZh: "等比数列",
    contentEn: "Sequence: 3, 6, 12, ... What is the 7th term?",
    contentZh: "数列3, 6, 12, ... 第7项是多少？",
    difficulty: "MEDIUM",
    category: "ALGEBRA",
    ageGroup: "AGE_14_16",
    answer: "192",
    answerExplainEn: "Ratio is 2. a7 = 3*2^6 = 192.",
    answerExplainZh: "公比是2。a7 = 3*2^6 = 192。",
    standards: ["CCSS-HSF-BF-A2"],
  },
  {
    titleEn: "Absolute Value Equation",
    titleZh: "绝对值方程",
    contentEn: "Solve |x - 4| = 3. Give the larger solution.",
    contentZh: "解|x-4|=3。写出较大的解。",
    difficulty: "MEDIUM",
    category: "ALGEBRA",
    ageGroup: "AGE_14_16",
    answer: "7",
    answerExplainEn: "x-4=3 or x-4=-3, so x=7 or 1. Larger is 7.",
    answerExplainZh: "x-4=3或x-4=-3，所以x=7或1。较大的是7。",
    standards: ["CCSS-HSA-REI-B3"],
  },
  {
    titleEn: "Factoring Quadratic",
    titleZh: "二次因式分解",
    contentEn: "Factor x^2 + 5x + 6. Enter the larger root of x^2 + 5x + 6 = 0.",
    contentZh: "分解x^2+5x+6。输入方程x^2+5x+6=0中较大的根。",
    difficulty: "MEDIUM",
    category: "ALGEBRA",
    ageGroup: "AGE_14_16",
    answer: "-2",
    answerExplainEn: "(x+2)(x+3)=0, roots are -2 and -3. The larger is -2.",
    answerExplainZh: "(x+2)(x+3)=0，根是-2和-3。较大的是-2。",
    standards: ["CCSS-HSA-SSE-B3", "CCSS-HSA-REI-B4"],
  },
  {
    titleEn: "Complete the Square Insight",
    titleZh: "配方法思路",
    contentEn: "For x^2 + 6x + 5 = 0, what value makes x^2 + 6x a perfect square trinomial?",
    contentZh: "对x^2+6x+5=0，给x^2+6x补成完全平方需要加多少？",
    difficulty: "HARD",
    category: "ALGEBRA",
    ageGroup: "AGE_16_18",
    answer: "9",
    answerExplainEn: "(6/2)^2=9.",
    answerExplainZh: "(6/2)^2=9。",
    standards: ["CCSS-HSA-REI-B4"],
  },
  {
    titleEn: "Distance Formula",
    titleZh: "两点距离公式",
    contentEn: "Distance between (1,2) and (4,6)?",
    contentZh: "点(1,2)和(4,6)之间距离是多少？",
    difficulty: "MEDIUM",
    category: "GEOMETRY",
    ageGroup: "AGE_14_16",
    answer: "5",
    answerExplainEn: "sqrt((4-1)^2 + (6-2)^2)=sqrt(9+16)=5.",
    answerExplainZh: "sqrt((4-1)^2 + (6-2)^2)=sqrt(9+16)=5。",
    standards: ["CCSS-HSG-GPE-B7"],
  },
  {
    titleEn: "Midpoint Formula",
    titleZh: "中点公式",
    contentEn: "Find the x-coordinate of midpoint of (2,9) and (8,1).",
    contentZh: "求点(2,9)和(8,1)中点的x坐标。",
    difficulty: "EASY",
    category: "GEOMETRY",
    ageGroup: "AGE_14_16",
    answer: "5",
    answerExplainEn: "(2+8)/2=5.",
    answerExplainZh: "(2+8)/2=5。",
    standards: ["CCSS-HSG-GPE-B4"],
  },
  {
    titleEn: "Circle Area",
    titleZh: "圆面积",
    contentEn: "A circle has radius 6. Using pi≈3.14, what is its area?",
    contentZh: "半径为6的圆，取pi≈3.14，面积是多少？",
    difficulty: "MEDIUM",
    category: "GEOMETRY",
    ageGroup: "AGE_14_16",
    answer: "113.04",
    answerExplainEn: "A=pi*r^2=3.14*36=113.04.",
    answerExplainZh: "A=pi*r^2=3.14*36=113.04。",
    standards: ["CCSS-HSG-C-B5"],
  },
  {
    titleEn: "Simple Interest",
    titleZh: "单利计算",
    contentEn: "Principal $500 at 4% simple interest for 3 years. Interest earned?",
    contentZh: "本金500美元，年利率4%，单利3年。利息是多少？",
    difficulty: "MEDIUM",
    category: "WORD_PROBLEMS",
    ageGroup: "AGE_14_16",
    answer: "60",
    answerExplainEn: "I=Prt=500*0.04*3=60.",
    answerExplainZh: "I=Prt=500*0.04*3=60。",
    standards: ["CCSS-HSN-Q-A1", "CCSS-HSA-CED-A1"],
  },
  {
    titleEn: "Piecewise Function",
    titleZh: "分段函数",
    contentEn: "f(x)=x+2 for x<0, and f(x)=x^2 for x>=0. Find f(-3).",
    contentZh: "f(x)在x<0时为x+2，在x>=0时为x^2。求f(-3)。",
    difficulty: "MEDIUM",
    category: "ALGEBRA",
    ageGroup: "AGE_16_18",
    answer: "-1",
    answerExplainEn: "Use first rule: -3+2=-1.",
    answerExplainZh: "用第一段：-3+2=-1。",
    standards: ["CCSS-HSF-IF-C7"],
  },
  {
    titleEn: "Radian Conversion",
    titleZh: "角度弧度转换",
    contentEn: "Convert 150° to radians (simplest form).",
    contentZh: "将150°转换为弧度（最简形式）。",
    difficulty: "MEDIUM",
    category: "TRIGONOMETRY",
    ageGroup: "AGE_14_16",
    answer: "5/6",
    answerExplainEn: "150° = 150/180 * pi = 5pi/6. Entered as coefficient 5/6.",
    answerExplainZh: "150° = 150/180*pi = 5pi/6。输入pi前系数5/6。",
    standards: ["CCSS-HSF-TF-A1"],
  },
  {
    titleEn: "Sine Special Angle",
    titleZh: "特殊角正弦",
    contentEn: "What is sin(30°)?",
    contentZh: "sin(30°)是多少？",
    difficulty: "EASY",
    category: "TRIGONOMETRY",
    ageGroup: "AGE_14_16",
    answer: "1/2",
    answerExplainEn: "sin(30°)=1/2.",
    answerExplainZh: "sin(30°)=1/2。",
    standards: ["CCSS-HSF-TF-A2"],
  },
  {
    titleEn: "Law of Exponents Division",
    titleZh: "指数除法法则",
    contentEn: "Simplify x^9 / x^4 for x != 0.",
    contentZh: "化简x^9 / x^4（x!=0）。",
    difficulty: "EASY",
    category: "ALGEBRA",
    ageGroup: "AGE_14_16",
    answer: "x^5",
    answerExplainEn: "Subtract exponents: x^(9-4)=x^5.",
    answerExplainZh: "同底数相除指数相减：x^(9-4)=x^5。",
    standards: ["CCSS-HSA-SSE-A1"],
  },
  {
    titleEn: "Polynomial Degree",
    titleZh: "多项式次数",
    contentEn: "What is the degree of 4x^5 - 2x^3 + 8?",
    contentZh: "4x^5 - 2x^3 + 8 的次数是多少？",
    difficulty: "EASY",
    category: "ALGEBRA",
    ageGroup: "AGE_14_16",
    answer: "5",
    answerExplainEn: "Highest power is 5.",
    answerExplainZh: "最高幂是5。",
    standards: ["CCSS-HSA-APR-A1"],
  },
  {
    titleEn: "Derivative Product Constant",
    titleZh: "常数倍求导",
    contentEn: "Find d/dx of 9x^3.",
    contentZh: "求9x^3的导数。",
    difficulty: "MEDIUM",
    category: "CALCULUS",
    ageGroup: "AGE_16_18",
    answer: "27x^2",
    answerExplainEn: "d/dx 9x^3 = 9*3x^2 = 27x^2.",
    answerExplainZh: "d/dx 9x^3 = 9*3x^2 = 27x^2。",
    standards: ["AP-CALC-AB-BIGIDEA2"],
  },
  {
    titleEn: "Derivative of e^x",
    titleZh: "e^x求导",
    contentEn: "Find d/dx of e^x.",
    contentZh: "求e^x的导数。",
    difficulty: "MEDIUM",
    category: "CALCULUS",
    ageGroup: "AGE_16_18",
    answer: "e^x",
    answerExplainEn: "Derivative of e^x is itself.",
    answerExplainZh: "e^x的导数还是e^x。",
    standards: ["AP-CALC-AB-BIGIDEA2"],
  },
  {
    titleEn: "Basic Limit",
    titleZh: "基础极限",
    contentEn: "Evaluate lim(x->2) (x^2 + 1).",
    contentZh: "求lim(x->2)(x^2+1)。",
    difficulty: "MEDIUM",
    category: "CALCULUS",
    ageGroup: "AGE_16_18",
    answer: "5",
    answerExplainEn: "Polynomial is continuous, substitute x=2: 4+1=5.",
    answerExplainZh: "多项式连续，直接代入x=2：4+1=5。",
    standards: ["AP-CALC-AB-BIGIDEA1"],
  },
  {
    titleEn: "Definite Integral Area",
    titleZh: "定积分面积",
    contentEn: "Compute integral from 0 to 2 of x dx.",
    contentZh: "计算从0到2的积分∫x dx。",
    difficulty: "HARD",
    category: "CALCULUS",
    ageGroup: "AGE_16_18",
    answer: "2",
    answerExplainEn: "Antiderivative x^2/2. Evaluate: 2^2/2 - 0 = 2.",
    answerExplainZh: "原函数x^2/2。代入上限下限得2。",
    standards: ["AP-CALC-AB-BIGIDEA3"],
  },
  {
    titleEn: "Conditional Probability",
    titleZh: "条件概率",
    contentEn: "If P(A and B)=0.2 and P(B)=0.5, what is P(A|B)?",
    contentZh: "若P(A且B)=0.2，P(B)=0.5，则P(A|B)是多少？",
    difficulty: "HARD",
    category: "PROBABILITY",
    ageGroup: "AGE_16_18",
    answer: "0.4",
    answerExplainEn: "P(A|B)=P(A and B)/P(B)=0.2/0.5=0.4.",
    answerExplainZh: "P(A|B)=P(A且B)/P(B)=0.2/0.5=0.4。",
    standards: ["CCSS-HSS-CP-A3"],
  },
  {
    titleEn: "Expected Value",
    titleZh: "期望值",
    contentEn: "A game pays $10 with probability 0.3 and $0 otherwise. What is expected value?",
    contentZh: "一个游戏以0.3概率得到10美元，否则0美元。期望值是多少？",
    difficulty: "MEDIUM",
    category: "STATISTICS",
    ageGroup: "AGE_16_18",
    answer: "3",
    answerExplainEn: "E=10*0.3 + 0*0.7 = 3.",
    answerExplainZh: "E=10*0.3 + 0*0.7 = 3。",
    standards: ["CCSS-HSS-MD-A2"],
  },
  {
    titleEn: "Z-Score",
    titleZh: "标准分数Z",
    contentEn: "Mean is 70, SD is 10, score is 90. What is z-score?",
    contentZh: "均值70，标准差10，分数90。z分数是多少？",
    difficulty: "MEDIUM",
    category: "STATISTICS",
    ageGroup: "AGE_16_18",
    answer: "2",
    answerExplainEn: "z=(90-70)/10=2.",
    answerExplainZh: "z=(90-70)/10=2。",
    standards: ["AP-STATS-UNIVARIATE"],
  },
  {
    titleEn: "Correlation Interpretation",
    titleZh: "相关系数解读",
    contentEn: "If correlation r = -0.9, is the linear relationship weak or strong? Answer strong.",
    contentZh: "若相关系数r=-0.9，线性关系是弱还是强？回答strong。",
    difficulty: "MEDIUM",
    category: "STATISTICS",
    ageGroup: "AGE_16_18",
    answer: "strong",
    answerExplainEn: "|r| close to 1 means strong linear relationship.",
    answerExplainZh: "|r|接近1表示线性关系强。",
    standards: ["AP-STATS-BIVARIATE"],
  },
];

export function buildUSK12QuestionBank(startSortOrder: number): SeedQuestion[] {
  const allBlueprints = [...BLUEPRINTS, ...HIGH_SCHOOL_EXTENSIONS];
  return allBlueprints.map((q, index) => {
    const { standards, ...question } = q;
    return {
      ...question,
    hints: [...DEFAULT_HINTS],
    animationConfig:
      q.animationConfig ?? { type: "number_journey", range: [0, 20], highlights: [] },
    funFactEn:
      q.funFactEn ??
      "This skill appears in US K-12 pathways including state standards and classroom assessments.",
    funFactZh:
      q.funFactZh ?? "这个知识点在美国K-12课程标准和课堂测评中都很常见。",
    isPublished: true,
    sortOrder: startSortOrder + index + 1,
    tags: standards ?? [],
    };
  });
}
